version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_DB_ADMIN_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      MONGO_DB_ADMIN_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
